name: Run DeepForest

on:
  workflow_dispatch:  # 手動実行

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DRIVE_FILE_ID: ${{ secrets.DRIVE_FILE_ID }}  # 秘密変数として登録

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run DeepForest prediction
        run: python run_deepforest.py
