name: DeepForest Predict

on:
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Clone deep-forest repo
        run: git clone https://github.com/leopiney/deep-forest.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pandas numpy scikit-learn google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Run script
        run: python run_deepforest.py
